eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
server:
  port: 8100
spring:
  application:
    name: feignfrontend
feign:
  hystrix:
    enabled: true


  client:
    config:
      default:
        requestInterceptors:
          com.config.HeaderInterceptor