

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/

server:
  port: 9001


spring:
  application:
    name:


jwt:
  header: jwtHeader
  secret: abcdefg
  expiration: 1800000   #毫秒